remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
    - jekyll-include-cache
    - jekyll-feed

paginate: 10 # amount of posts to show
paginate_path: /page:num/
include:
    - _pages

title: "arty-hlr"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      share: true
      related: true
